### ISSUE TITLE
Having trouble running DDPG implementation

### ISSUE THREAD

**Issue by suryabhupa** [sfujim/TD3#1]
I'm using Python 3.4 and PyTorch 0.4 on Mac OS X; running 

`python main.py --env HalfCheetah-v1 --policy_name DDPG`

results in:

```
(my_root) sbhupatiraju@instance-11:~/ddpg/TD3$ python main.py --env HalfCheetah-v1 --policy_name DDPG
---------------------------------------
Settings: DDPG_HalfCheetah-v1_0
---------------------------------------
[2018-05-01 17:37:35,924] Making new env: HalfCheetah-v1
/home/sbhupatiraju/ddpg/TD3/DDPG.py:19: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  return Variable(tensor, volatile=volatile)
---------------------------------------
Evaluation over 10 episodes: -1.481050
---------------------------------------
Total T: 1000 Episode Num: 1 Episode T: 1000 Reward: -409.138651
/home/sbhupatiraju/ddpg/TD3/DDPG.py:97: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  target_Q.volatile = False
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    policy.train(replay_buffer, episode_timesteps, args.batch_size, args.discount, args.tau)
  File "/home/sbhupatiraju/ddpg/TD3/DDPG.py", line 104, in train
    critic_loss = self.criterion(current_Q, target_Q)
  File "/home/sbhupatiraju/.conda/envs/my_root/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sbhupatiraju/.conda/envs/my_root/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 371, in forward
    _assert_no_grad(target)
  File "/home/sbhupatiraju/.conda/envs/my_root/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 12, in _assert_no_grad
    "nn criterions don't compute the gradient w.r.t. targets - please " \
AssertionError: nn criterions don't compute the gradient w.r.t. targets - please mark these tensors as not requiring gradients
```

**Comment by sfujim** [comment]
The code was original run on python 2.7 and pytorch 0.2.0_4, although there shouldn't be issues with anything before 0.4. I intend on updating this to accomodate newer versions of pytorch at some point in the future.

I don't have time to check pytorch 0.4 right now, but fortunately it looks like your issue is relatively simple. Since volatile is depreciated, you should be able to get the same behavior by replacing lines 15-19 with: 

```
def var(tensor, volatile=False):
	if torch.cuda.is_available():
		return Variable(tensor, requires_grad=volatile).cuda()
	else:
		return Variable(tensor, requires_grad=volatile)
```

Let me know if that works. There may be other issues introduced by pytorch 0.4, since its not backwards compatible.
